AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 115

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
