AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 160

Metrics/ModuleLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Max: 8

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 115

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
